### ISSUE TITLE
How to use this package with multiple DBs?

### ISSUE THREAD

**Issue by brandonmailhiot** [dialoguemd/fastapi-sqla#102]
Could not find documentation about whether this is or isn't supported. It would be great if I could get some guidance on how I can set up my service to use 2+ DBs. I specifically need to read from one Postgres DB and write to two Postgres DBs.

**Comment by hadrien** [comment]
Hi @brandonmailhiot,

It is not something supported.

We [@dialogue](https://github.com/dialoguemd/) are in a need of a read only session to the same db. So this is something we will implement eventually.

**Comment by hadrien** [comment]
@brandonmailhiot FYI we started https://github.com/dialoguemd/fastapi-sqla/pull/105 
Should be released by the end of next week.

**Comment by arththebird** [comment]
This is now supported with version 3.0.0. See the [release notes](https://github.com/dialoguemd/fastapi-sqla/releases/tag/v3.0.0) for more details.
