### ISSUE TITLE
Async dependencies of the pytest plugin are required even when you only use the sync variants

### ISSUE THREAD

**Issue by sbstp** [dialoguemd/fastapi-sqla#34]
In my project I chose to use pyscopg2 instead of asyncpg. I did not have any issues with this until I got to the tests. I had to install `pytest-asyncio` and `asyncpg` to please the pytest fixtures.

Unfortunately even after installing the dependencies I still get an error:
```python
    @fixture(scope="session")
    def asyncpg_url(db_url):
>       scheme, parts = db_url.split(":")
E       ValueError: too many values to unpack (expected 2)
```

My connection string looks like `postgresql+psycopg2://app:*****@localhost:4200/app_test`, so there's more than 2 parts created by splitting on `':'`.

I found a work-around in the meantime, it's to override the `patch_async_sessionmaker` fixture which has `autouse=True`, with this
```python
@fixture(autouse=True)
async def patch_async_sessionmaker():
    pass
```
It doesn't cause me trouble to disable it because I only use the sync version of the fixtures.

**Comment by hadrien** [comment]
@sbstp Thanks for reporting, it should be fixed by #35 
FYI I may not have a review approval before Monday end of day.

**Comment by hadrien** [comment]
🎉  It should be fixed.

**Comment by sbstp** [comment]
Thanks, I tested it and it indeed works well.
