### ISSUE TITLE
Versions 2.5.0 or 2.4.0 not found in PyPi

### ISSUE THREAD

**Issue by abnerjacobsen** [dialoguemd/fastapi-sqla#66]
@hadrien Neither version is available on PyPi.

Regards,

**Comment by hadrien** [comment]
sorry for that, it's fixed!

https://pypi.org/project/fastapi-sqla/#history

**Comment by hadrien** [comment]
@abnerjacobsen FYI publish job failed because of a dependency. It has been fixed in #67

**Comment by abnerjacobsen** [comment]
@hadrien I think there is an error in README.md, where it reads:

`from fastapi_sqla import Base, Page, AsyncPagination, AsyncSession`

Should be:

```
from fastapi_sqla import Base, Page
from fastapi_sqla.asyncio_support import AsyncPaginate, AsyncPagination
```

I tried to use asynchronous pagination importing modules as described in the README and got an import error.

**Comment by hadrien** [comment]
@abnerjacobsen FYI, thanks for reporting, it has been fixed. You can now import the async components directly from `fastapi_sqla`
