### ISSUE TITLE
Enabling shared in-memory sqlite db to be shared between sync and async engines/sessions

### ISSUE THREAD

**Issue by joeblackwaslike** [dialoguemd/fastapi-sqla#75]
So I just discovered your repo here and it's been very useful considering how difficult it can be to marry sqlalchemy with an async framework and pytest with integration tests running against a sqlite in-memory database.  I think many of these issues come from various gotchas around async pytest fixtures, async context managers, and ContextVars, so having such a reference known to work correctly has been really valuable.

I wanted to reciprocate by sharing a method which allows for multiple sqlalchemy engines to share the same underlying in-memory database and cache.  It utilizes sqlite's uri filename feature to define a virtual filename handle (no files are created) with a shared cache.  Whenever you use the same virtual filename handle and set cache=shared, they map to the same in-memory database.  I tend to use this when I want both async and sync engines to see the updates being made from the other, and it supports savepoint based subtransactions.  It's really quite simple to implement.

1. synchronous engine should define the database uri as: `"sqlite:///file:temp.db?mode=memory&cache=shared&uri=true"`.
   ```python
   create_engine("sqlite:///file:temp.db?mode=memory&cache=shared&uri=true")
   ```
2. asynchronous engine should define the database uri as: `"sqlite+aiosqlite:///file:temp.db?mode=memory&cache=shared&uri=true"`.
   ```python
   create_async_engine("sqlite+aiosqlite:///file:temp.db?mode=memory&cache=shared&uri=true")
   ```

Some details can be read at the following resources:
* https://www.sqlite.org/inmemorydb.html
* https://www.bricelam.net/2015/12/10/shareable-in-memory-databases.html
* https://ricardoanderegg.com/posts/python-multiple-shared-in-memory-sqlite-databases/

**Comment by hadrien** [comment]
Thanks a lot for sharing @joeblackwaslike. 

(Closing as it is not an issue, will open the Discussion tab to allow better conversations in the future.)
